// ==============================================================================
// Lankora: Rich Sri Lankan Mock Data & Offline Fallback
// Covers major provinces: Central, Southern, Eastern, Northern, Cultural Triangle
// ==============================================================================

import { Destination, Experience, Place, Restaurant, Stay, Review, Trip } from '@/types';

export const MOCK_DESTINATIONS: Destination[] = [
  {
    id: 'dest-ella',
    name: 'Ella',
    slug: 'ella',
    short_description: 'Misty mountain gap flanked by emerald Ceylon tea hills, cascades, and railway bridges.',
    description: 'Perched in the Uva highlands at 1,041 meters altitude, Ella is Sri Lanka’s bohemian hill haven. Wrapped in morning fog that burns away to reveal breathtaking views through the Ella Gap, this mountain town is beloved for hiking Little Adam’s Peak, admiring the century-old Nine Arch Bridge enveloped in jungle, and lingering in open-air cafes surrounded by cool forest air.',
    province: 'Uva Province',
    district: 'Badulla',
    latitude: 6.8667,
    longitude: 81.0466,
    hero_image: 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'December to April',
    estimated_budget: '$45 - $85 / day',
    category: 'Hill Country',
    highlights: ['Nine Arch Bridge train crossing', 'Little Adam’s Peak sunrise', 'Ravana Pool Club & Falls', 'Demodara Loop railway'],
    vibe_tags: ['Misty Hills', 'Hiking', 'Pure Ceylon Tea', 'Cafe Culture'],
    rating: 4.9,
    review_count: 342,
    is_featured: true,
    is_hidden_gem: false,
  },
  {
    id: 'dest-sigiriya',
    name: 'Sigiriya',
    slug: 'sigiriya',
    short_description: 'The monolithic 5th-century Lion Citadel rising 200m from ancient tropical rainforest.',
    description: 'An architectural and artistic marvel of the ancient world, Sigiriya (Lion Rock) was transformed in 477 AD by King Kashyapa into an impenetrable sky citadel. Ascend through gravity-defying terraces, marvel at ancient celestial fresco paintings that retained their vibrant ochre and cinnabar pigments for 1,500 years, pass through titanic stone lion paws, and survey the endless green wilderness.',
    province: 'Central Province',
    district: 'Matale',
    latitude: 7.9570,
    longitude: 80.7603,
    hero_image: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1578637387939-43c525550085?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'January to April',
    estimated_budget: '$50 - $110 / day',
    category: 'Cultural Triangle',
    highlights: ['Lion Rock Fortress climb', 'Pidurangala sunrise panorama', 'Ancient water gardens & moats', 'Frescoes of the Cloud Maidens'],
    vibe_tags: ['UNESCO Wonder', 'Ancient Citadel', 'Panoramic', 'Archaeology'],
    rating: 4.9,
    review_count: 512,
    is_featured: true,
    is_hidden_gem: false,
  },
  {
    id: 'dest-galle',
    name: 'Galle Fort',
    slug: 'galle',
    short_description: 'Living 17th-century Dutch colonial ocean fortress with cobblestone alleys and artisan boutiques.',
    description: 'Bounded by thick ocean ramparts that resist the battering of Indian Ocean breakers, Galle Fort is an extraordinary living colonial monument. Portuguese, Dutch, and British merchant history fuses with tropical Sri Lankan warmth. Walk cobblestone lanes lined with Dutch merchant mansions, historic jewelers, fragrant cinnamon bakeries, and watch golden sunsets from the iconic white Lighthouse.',
    province: 'Southern Province',
    district: 'Galle',
    latitude: 6.0329,
    longitude: 80.2168,
    hero_image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'October to April',
    estimated_budget: '$60 - $140 / day',
    category: 'Southern Coast',
    highlights: ['Point Utrecht Lighthouse sunset', 'Ramparts ocean bastion stroll', 'Dutch Hospital dining precinct', 'Antique & gem boutiques'],
    vibe_tags: ['Colonial Living', 'Ocean Breeze', 'Artisan Coffee', 'Romance'],
    rating: 4.8,
    review_count: 420,
    is_featured: true,
    is_hidden_gem: false,
  },
  {
    id: 'dest-mirissa',
    name: 'Mirissa',
    slug: 'mirissa',
    short_description: 'Golden crescent beach, coconut promontories, and the world’s greatest blue whale corridor.',
    description: 'Mirissa captures the carefree spirit of southern island life. It is globally recognized as one of the best locations on Earth to view majestic blue whales and spinner dolphins. Golden sandy bays, rolling beginner-friendly surf waves, the iconic reddish clay promontory of Coconut Tree Hill, and twilight candlelit seafood barbecues right on the sand make Mirissa unforgettable.',
    province: 'Southern Province',
    district: 'Matara',
    latitude: 5.9483,
    longitude: 80.4578,
    hero_image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'November to April',
    estimated_budget: '$40 - $80 / day',
    category: 'Southern Coast',
    highlights: ['Blue Whale migration cruise', 'Coconut Tree Hill at dawn', 'Secret Beach hideaway', 'Parrot Rock reef bridge'],
    vibe_tags: ['Whale Safari', 'Golden Sands', 'Sunset Drinks', 'Surf Life'],
    rating: 4.8,
    review_count: 290,
    is_featured: true,
    is_hidden_gem: false,
  },
  {
    id: 'dest-yala',
    name: 'Yala National Park',
    slug: 'yala',
    short_description: 'Arid coastal savanna and thorny scrub home to the highest leopard density on the planet.',
    description: 'Where jungle wilderness embraces the Indian Ocean shoreline, Yala National Park is Sri Lanka’s premier safari territory. Board an open-top 4x4 with an expert naturalist tracker to witness leopards resting on granite boulders, wild elephant herds drinking at waterholes, sloth bears digging for termites, and crocodiles basking beneath the afternoon sun.',
    province: 'Southern / Uva',
    district: 'Hambantota',
    latitude: 6.3725,
    longitude: 81.5170,
    hero_image: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'February to July',
    estimated_budget: '$90 - $220 / day',
    category: 'Wildlife Safari',
    highlights: ['Block 1 Leopard tracking', 'Elephant family sightings', 'Coastal sand dunes', 'Birdwatching at Sithulpawwa'],
    vibe_tags: ['Apex Predators', 'Wild Safari', 'Raw Nature', 'Jeep Expeditions'],
    rating: 4.9,
    review_count: 460,
    is_featured: true,
    is_hidden_gem: false,
  },
  {
    id: 'dest-kandy',
    name: 'Kandy',
    slug: 'kandy',
    short_description: 'Sacred mountain kingdom nestled around an emerald lake, preserving ancient Buddhist relics.',
    description: 'The last sovereign Sinhalese kingdom before British conquest, Kandy remains the cultural capital of Sri Lanka. Cradled by mist-cloaked mountain ranges, the city centers around the tranquil Kandy Lake and the gold-roofed Temple of the Sacred Tooth Relic (Sri Dalada Maligawa). Experience royal botanical gardens, Kandyan fire dancers, and rich culinary traditions.',
    province: 'Central Province',
    district: 'Kandy',
    latitude: 7.2906,
    longitude: 80.6337,
    hero_image: 'https://images.unsplash.com/photo-1578637387939-43c525550085?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'December to April',
    estimated_budget: '$40 - $90 / day',
    category: 'Cultural Triangle',
    highlights: ['Temple of the Tooth Relic ceremony', 'Peradeniya Royal Botanical Gardens', 'Kandy Lake promenade', 'Kandyan drumming & dance'],
    vibe_tags: ['Sacred Kingdom', 'Royal Heritage', 'Lake Reflection', 'Ceremony'],
    rating: 4.7,
    review_count: 380,
    is_featured: false,
    is_hidden_gem: false,
  },
  {
    id: 'dest-nuwara-eliya',
    name: 'Nuwara Eliya',
    slug: 'nuwara-eliya',
    short_description: 'Cool alpine highland valley famed for verdant tea estates, roses, and colonial nostalgia.',
    description: 'Known as "Little England", Nuwara Eliya sits at 1,868 meters elevation beneath Sri Lanka’s highest peak. Crisp alpine mountain air, manicured tea bushes stretching to the horizon, Tudor-style country bungalows, strawberry farms, and sailing on Lake Gregory make this a distinct highland escape.',
    province: 'Central Province',
    district: 'Nuwara Eliya',
    latitude: 6.9497,
    longitude: 80.7891,
    hero_image: 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'March to May',
    estimated_budget: '$55 - $120 / day',
    category: 'Hill Country',
    highlights: ['High Tea at The Grand Hotel', 'Pedro Tea Estate vintage factory', 'Horton Plains World’s End cliff', 'Lake Gregory twilight stroll'],
    vibe_tags: ['Alpine Cool', 'Ceylon Tea Estates', 'Tudor Mansions', 'Waterfalls'],
    rating: 4.7,
    review_count: 310,
    is_featured: false,
    is_hidden_gem: false,
  },
  {
    id: 'dest-arugam-bay',
    name: 'Arugam Bay',
    slug: 'arugam-bay',
    short_description: 'World-renowned point break surf mecca and bohemian eastern lagoon sanctuary.',
    description: 'On the sun-drenched southeastern coast, Arugam Bay draws ocean lovers and wanderers from around the globe. Famous for its long, peeling right-hand point breaks, sandy hammocks, yoga shalas, and surrounding lagoons where wild elephants roam peacefully alongside migratory waterbirds.',
    province: 'Eastern Province',
    district: 'Ampara',
    latitude: 6.8436,
    longitude: 81.8344,
    hero_image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'May to September',
    estimated_budget: '$35 - $75 / day',
    category: 'Eastern Coast',
    highlights: ['Main Point barrel surfing', 'Kottukal Lagoon wild safari', 'Panama sand dunes at sunset', 'Beach bonfires & smoothie bowls'],
    vibe_tags: ['World-Class Surf', 'Bohemian', 'Lagoon Wildlife', 'Sunrise Swells'],
    rating: 4.8,
    review_count: 210,
    is_featured: false,
    is_hidden_gem: true,
  },
  {
    id: 'dest-jaffna',
    name: 'Jaffna',
    slug: 'jaffna',
    short_description: 'Vibrant Tamil heritage, ornate Hindu kovils, palmyrah palms, and fiery crab curries.',
    description: 'At the northernmost tip of the island, Jaffna offers an entirely distinct cultural experience. Marked by soaring gopurams of Nallur Kandaswamy Kovil, vast lagoons lined with palmyrah trees, Dutch star forts, island boat hops to Delft, and the boldest seafood cuisine in South Asia.',
    province: 'Northern Province',
    district: 'Jaffna',
    latitude: 9.6615,
    longitude: 80.0255,
    hero_image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'January to September',
    estimated_budget: '$35 - $70 / day',
    category: 'Northern Heritage',
    highlights: ['Nallur Kandaswamy Kovil', 'Jaffna Dutch Fort sunset', 'Delft Island wild ponies', 'Spicy Jaffna Crab Curry feast'],
    vibe_tags: ['Tamil Heritage', 'Fiery Cuisine', 'Palmyrah Haven', 'Authentic'],
    rating: 4.8,
    review_count: 180,
    is_featured: false,
    is_hidden_gem: true,
  },
  {
    id: 'dest-trincomalee',
    name: 'Trincomalee',
    slug: 'trincomalee',
    short_description: 'Deep natural harbor, turquoise Pigeon Island reefs, and cliffside ancient shrines.',
    description: 'On Sri Lanka’s eastern shores, Trincomalee boasts one of the finest natural harbors in history. Snorkel among blacktip reef sharks at Pigeon Island National Park, explore the cliffside Koneswaram Kovil overlooking Swami Rock, and unwind on untouched white sands of Nilaveli.',
    province: 'Eastern Province',
    district: 'Trincomalee',
    latitude: 8.5874,
    longitude: 81.2152,
    hero_image: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'April to October',
    estimated_budget: '$45 - $95 / day',
    category: 'Eastern Coast',
    highlights: ['Pigeon Island coral snorkeling', 'Koneswaram Temple on Swami Rock', 'Nilaveli beach tranquility', 'Whale watching in the deep trench'],
    vibe_tags: ['Coral Reefs', 'Turquoise Waters', 'Sacred Cliffs', 'Deep Harbor'],
    rating: 4.7,
    review_count: 195,
    is_featured: false,
    is_hidden_gem: true,
  },
  {
    id: 'dest-anuradhapura',
    name: 'Anuradhapura',
    slug: 'anuradhapura',
    short_description: 'First ancient kingdom featuring colossal stupas and the oldest documented tree on Earth.',
    description: 'The grand capital of ancient Sri Lanka for over a millennium, Anuradhapura is a sacred archaeological sanctuary. Mammoth white brick stupas like Ruwanwelisaya rise hundreds of feet into the sky, while the sacred Jaya Sri Maha Bodhi — planted in 288 BC — continues to be revered by pilgrims from across the globe.',
    province: 'North Central Province',
    district: 'Anuradhapura',
    latitude: 8.3114,
    longitude: 80.4037,
    hero_image: 'https://images.unsplash.com/photo-1578637387939-43c525550085?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'May to September',
    estimated_budget: '$40 - $80 / day',
    category: 'Cultural Triangle',
    highlights: ['Ruwanwelisaya Stupa reflection', 'Jaya Sri Maha Bodhi tree', 'Twin Ponds (Kuttam Pokuna)', 'Bicycle tours among ancient ruins'],
    vibe_tags: ['Ancient Capital', 'Giant Stupas', 'Sacred Bodhi', 'Serene Ruins'],
    rating: 4.8,
    review_count: 260,
    is_featured: false,
    is_hidden_gem: false,
  },
  {
    id: 'dest-hikkaduwa',
    name: 'Hikkaduwa',
    slug: 'hikkaduwa',
    short_description: 'Lively marine sanctuary, giant sea turtles grazing in shallows, and surf vibes.',
    description: 'One of Sri Lanka’s original beach discoveries, Hikkaduwa combines vibrant coastal nightlife with calm reef shallows. Giant green sea turtles swim directly to the beach each morning, while offshore coral gardens and outer reef surf breaks entertain divers and wave riders.',
    province: 'Southern Province',
    district: 'Galle',
    latitude: 6.1408,
    longitude: 80.1009,
    hero_image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'
    ],
    best_time_to_visit: 'November to April',
    estimated_budget: '$35 - $75 / day',
    category: 'Southern Coast',
    highlights: ['Feeding wild sea turtles in the bay', 'Coral reef snorkeling', 'Benny’s surf point', 'Sunset beach drums'],
    vibe_tags: ['Sea Turtles', 'Coral Bay', 'Nightlife', 'Surf Town'],
    rating: 4.6,
    review_count: 230,
    is_featured: false,
    is_hidden_gem: false,
  }
];

export const MOCK_PLACES: Place[] = [
  {
    id: 'place-nine-arch',
    destination_id: 'dest-ella',
    name: 'Nine Arch Bridge',
    description: 'Commissioned under the British Raj and engineered with Sri Lankan stonemasons, this viaduct spans 91 meters through thick jungle valley without using a single structural steel girder.',
    location: 'Demodara, Ella',
    latitude: 6.8767,
    longitude: 81.0608,
    images: ['https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=800&q=80'],
    category: 'Heritage',
    opening_hours: 'Open 24 Hours',
    entry_fee: 'Free',
    tips: 'Watch for the blue passenger train around 9:20 AM, 11:45 AM, and 3:30 PM for postcard views.',
    rating: 4.9,
    review_count: 640
  },
  {
    id: 'place-pidurangala',
    destination_id: 'dest-sigiriya',
    name: 'Pidurangala Rock',
    description: 'An ancient monastery peak adjacent to Sigiriya that offers the ultimate unobstructed panoramic view of the Lion Rock surrounded by endless jungle canopy.',
    location: 'Sigiriya',
    latitude: 7.9650,
    longitude: 80.7630,
    images: ['https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80'],
    category: 'Viewpoint',
    opening_hours: '5:00 AM – 6:30 PM',
    entry_fee: 'LKR 1,000 (~$3)',
    tips: 'Climb 45 minutes before sunrise. Bring a headlamp and wear covered shoulders to pass through the monastery gate.',
    rating: 4.9,
    review_count: 480
  },
  {
    id: 'place-galle-lighthouse',
    destination_id: 'dest-galle',
    name: 'Galle Fort Lighthouse',
    description: 'Constructed in 1939 on Point Utrecht Bastion, this iconic white 26.5m lighthouse is framed by soaring palm trees looking out across the emerald ocean.',
    location: 'Ramparts, Galle Fort',
    latitude: 6.0267,
    longitude: 80.2174,
    images: ['https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80'],
    category: 'Heritage',
    opening_hours: 'Open 24 Hours',
    entry_fee: 'Free',
    tips: 'A magical gathering point at twilight when local kite-flyers and strollers assemble on the sea wall.',
    rating: 4.8,
    review_count: 350
  },
  {
    id: 'place-coconut-hill',
    destination_id: 'dest-mirissa',
    name: 'Coconut Tree Hill',
    description: 'A striking dome-shaped red clay headland lined with tall curved palm trees looking out over the endless Indian Ocean.',
    location: 'Mirissa East',
    latitude: 5.9442,
    longitude: 80.4632,
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'],
    category: 'Viewpoint',
    opening_hours: 'Open 24 Hours',
    entry_fee: 'Free',
    tips: 'Arrive at 6:15 AM to experience sunrise before crowds arrive.',
    rating: 4.8,
    review_count: 410
  }
];

export const MOCK_EXPERIENCES: Experience[] = [
  {
    id: 'exp-blue-train',
    destination_id: 'dest-ella',
    title: 'Scenic Hill Country Blue Train Crossing',
    description: 'The journey from Nanu Oya to Ella is revered as one of the most magnificent railway journeys on earth. Lean out the open doorway as mist swirls over tea pickers and roaring ravines.',
    category: 'Adventure',
    duration: '3.5 Hours',
    price: '$15 / seat',
    images: ['https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=800&q=80'],
    location: 'Nanu Oya / Nuwara Eliya to Ella',
    host_name: 'Sri Lanka Railways & Local Porter',
    inclusions: ['Reserved window seat', 'Masala chai & wade snacks', 'Luggage assist'],
    rating: 4.9,
    review_count: 890
  },
  {
    id: 'exp-yala-safari',
    destination_id: 'dest-yala',
    title: 'Dawn Leopard & Wildlife Safari in Yala',
    description: 'A bespoke 4x4 open safari jeep journey led by an experienced wildlife tracker deep into Block 1 to encounter leopards, sloth bears, wild elephants, and spotted deer.',
    category: 'Wildlife',
    duration: 'Full Day',
    price: '$95 / person',
    images: ['https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=800&q=80'],
    location: 'Yala Block 1 Entrance',
    host_name: 'Naturalist Janaka Perera',
    inclusions: ['Private 4x4 Safari Jeep', 'Park permits', 'Bush breakfast picnic', 'High-power binoculars'],
    rating: 4.9,
    review_count: 380
  },
  {
    id: 'exp-cooking-class',
    destination_id: 'dest-galle',
    title: 'Village Spice Harvest & Clay-Pot Curry Class',
    description: 'Walk through an aromatic family organic garden picking cinnamon and curry leaves, scrape fresh coconuts on traditional benches, and cook seven distinct curries over wood fires.',
    category: 'Culinary',
    duration: '4 Hours',
    price: '$38 / person',
    images: ['https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80'],
    location: 'Spice Garden, Unawatuna',
    host_name: 'Amma Malini',
    inclusions: ['7-curry organic feast', 'Clay pot cooking lessons', 'Recipe book', 'Hand-ground spice gifts'],
    rating: 5.0,
    review_count: 240
  },
  {
    id: 'exp-mirissa-whales',
    destination_id: 'dest-mirissa',
    title: 'Responsible Blue Whale & Dolphin Sea Safari',
    description: 'Venture into the southern shipping trench with marine conservation guides to encounter giant blue whales, humpbacks, and acrobatic spinner dolphin pods.',
    category: 'Wildlife',
    duration: '4.5 Hours',
    price: '$55 / person',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'],
    location: 'Mirissa Harbor',
    host_name: 'Captain Danushka & Marine Biologist',
    inclusions: ['Catamaran cruise', 'Fresh tropical breakfast', 'Life jackets', 'Marine mammal hydrophone audio'],
    rating: 4.8,
    review_count: 310
  }
];

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-cafe-chill',
    destination_id: 'dest-ella',
    name: 'Cafe Chill Ella',
    description: 'An iconic multi-story bamboo establishment serving flavorful Sri Lankan clay pot lamprais, gourmet burgers, and fresh passion fruit smoothies in a social mountain atmosphere.',
    cuisine: 'Ceylon Fusion & Cafe',
    price_range: '$$',
    location: 'Main Street, Ella',
    must_try: ['Traditional Chicken Lamprais', 'Pol Roti burger with seeni sambol', 'Passion fruit mint crusher'],
    images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80'],
    rating: 4.8,
    review_count: 520
  },
  {
    id: 'rest-fort-printers',
    destination_id: 'dest-galle',
    name: 'The Fort Printers',
    description: 'An elegant 18th-century heritage printing mansion courtyard serving sustainably sourced yellowfin tuna, coconut lemongrass curry, and crisp tropical cocktails.',
    cuisine: 'Fine Coastal Dining',
    price_range: '$$$',
    location: 'Pedlar Street, Galle Fort',
    must_try: ['Seared Sesame Tuna', 'Negombo crab bisque ravioli', 'Kithul treacle tart'],
    images: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80'],
    rating: 4.9,
    review_count: 290
  }
];

export const MOCK_STAYS: Stay[] = [
  {
    id: 'stay-98-acres',
    destination_id: 'dest-ella',
    name: '98 Acres Resort & Spa',
    description: 'A boutique luxury eco-retreat constructed using recycled timber, thatch, and rough-hewn stone, set on a 98-acre working tea estate facing Little Adam’s Peak.',
    type: 'Eco-Lodge',
    price_range: '$190 - $380 / night',
    amenities: ['Infinity mountain pool', 'Ayurveda tea spa', 'Tea estate trekking', 'Helipad', 'Valley balcony'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80'],
    rating: 4.9,
    review_count: 310,
    location: 'Passara Road, Ella'
  },
  {
    id: 'stay-amangalla',
    destination_id: 'dest-galle',
    name: 'Amangalla Galle Fort',
    description: 'A legendary 300-year-old grand dame within the fort walls featuring original Burmese teak floorboards, antique four-poster beds, and the storied Zaal veranda.',
    type: 'Colonial Villa',
    price_range: '$380 - $750 / night',
    amenities: ['The Baths hydrotherapy spa', 'Shaded garden pool', 'Private butler service', 'Antique library bar'],
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80'],
    rating: 5.0,
    review_count: 180,
    location: 'Church Street, Galle Fort'
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    user_id: 'user-elena',
    user_name: 'Elena Rostova',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    target_type: 'destination',
    target_id: 'dest-ella',
    rating: 5,
    comment: 'Ella was the emotional highlight of our two weeks in Sri Lanka. Standing on Nine Arch Bridge as the morning mist rolled across the tea leaves felt like stepping into an oil painting. Don’t miss sunrise at Little Adam’s Peak!',
    created_at: '2026-09-15T08:30:00Z'
  },
  {
    id: 'rev-2',
    user_id: 'user-marcus',
    user_name: 'Marcus Chen',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    target_type: 'experience',
    target_id: 'exp-blue-train',
    rating: 5,
    comment: 'The blue train from Nuwara Eliya down to Ella exceeded every expectation. Sitting on the open doorway while the breeze carried the fragrance of fresh eucalyptus and tea was unforgettable.',
    created_at: '2026-09-20T14:15:00Z'
  }
];

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip-southern-highlands',
    user_id: 'current-user',
    title: 'Highlands & Southern Coast Explorer',
    start_date: '2026-10-12',
    end_date: '2026-10-20',
    description: 'From misty tea terraces in Ella to colonial ocean ramparts in Galle and wildlife safaris in Yala.',
    cover_image: 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=800&q=80',
    destinations: ['Ella', 'Yala', 'Galle Fort', 'Mirissa'],
    travel_style: 'Curated Adventure',
    status: 'planning',
    items: [
      {
        id: 'item-1',
        trip_id: 'trip-southern-highlands',
        target_type: 'experience',
        target_id: 'exp-blue-train',
        title: 'Scenic Hill Country Blue Train Crossing',
        day_number: 1,
        start_time: '09:30 AM',
        end_time: '01:00 PM',
        notes: 'Sit on the left side of the carriage for optimal valley vistas.',
        location: 'Ella Railway Station',
        order_index: 0
      },
      {
        id: 'item-2',
        trip_id: 'trip-southern-highlands',
        target_type: 'place',
        target_id: 'place-nine-arch',
        title: 'Nine Arch Bridge Twilight Walk',
        day_number: 1,
        start_time: '04:30 PM',
        end_time: '06:00 PM',
        notes: 'Walk along the tracks from the jungle path beside Cafe Chill.',
        location: 'Demodara, Ella',
        order_index: 1
      },
      {
        id: 'item-3',
        trip_id: 'trip-southern-highlands',
        target_type: 'experience',
        target_id: 'exp-yala-safari',
        title: 'Dawn Leopard & Wildlife Safari',
        day_number: 3,
        start_time: '05:45 AM',
        end_time: '12:00 PM',
        notes: 'Tracker Janaka will pick us up from the lodge gate.',
        location: 'Yala Block 1',
        order_index: 0
      }
    ],
    created_at: '2026-09-22T10:00:00Z'
  }
];
